### ISSUE TITLE
CSS reset

### ISSUE THREAD

**Issue by volodymyr-kushnir** [volodymyrkryvytskyy/homepage#26]
Issue рішив додати не стільки через те, що є якісь критичні проблеми, як через те, щоб висловити свої враження, тому перш за все — **well done**, сміявся з "работи в командкє". Ну і раз я вже тут, то дозволю собі зауважити, що там на сайті нема ресету CSS і тому `<body>` має лишній дефолтний margin. Можна самому виставити то в 0 руками, а можна додати якийсь CSS reset від Meyer'а або Normalize.css, наприклад.

**Comment by volodymyr-kushnir** [comment]
> **A\*\*\*\*\*\*r T\*\*\*\*\*h [14:00]**
> а ты не видел тот видос который он прикрепил?
>**Volodymyr Kushnir [14:00]**
> ВІІІІДОООООС?!
>**A\*\*\*\*\*\*r T\*\*\*\*\*h [14:01]**
> на аватарку кликни. этот видос это яд)

@volodymyrkryvytskyy, це успєх!

**Comment by vkryvytskyi** [comment]
Так так, что-то я исправлял исправлял, а работа как была в командке, так и осталась:(
Спасибо за подсказку, ресет сейчас тоже добавлю!

**Comment by volodymyr-kushnir** [comment]
А, я думав шо то спеціально так! Звучало смішно, я б лишав так, справді (: Ну але ладно вже.
